# Generated by Django 3.2.19 on 2023-08-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='is_by_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='is_by_approval',
            field=models.BooleanField(default=False),
        ),
    ]
