# Generated by Django 3.2.19 on 2023-08-18 20:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0015_discussiontopiclink_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerfilter',
            name='allow',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('legacy', 'legacy'), ('openedx', 'openedx'), ('ed-discuss', 'ed-discuss'), ('inscribe', 'inscribe'), ('piazza', 'piazza'), ('yellowdig', 'yellowdig')], max_length=20), blank=True, help_text='Liste de fournisseurs séparés par des virgules à autoriser, par exemple: legacy,openedx,ed-discuss,inscribe,piazza,yellowdig', max_length=63, size=3, verbose_name='Allow List'),
        ),
        migrations.AlterField(
            model_name='providerfilter',
            name='deny',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('legacy', 'legacy'), ('openedx', 'openedx'), ('ed-discuss', 'ed-discuss'), ('inscribe', 'inscribe'), ('piazza', 'piazza'), ('yellowdig', 'yellowdig')], max_length=20), blank=True, help_text='Liste de fournisseurs séparés par des virgules à refuser, par exemple: legacy,openedx,ed-discuss,inscribe,piazza,yellowdig', max_length=63, size=3, verbose_name='Deny List'),
        ),
    ]
