# Generated by Django 3.2.19 on 2023-08-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
